apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce # Can be used for read and write by a single node
  resources:
    requests:
      storage: 0.1Gi # 100MB storage