apiVersion: v1
kind: Service # Service object
metadata:
  name: express-server-cluster-ip-service
spec: # Service configuration
  type: ClusterIP
  selector:
    component: express-server # Same as pod metadata. What set of pods this service should provide access to.
  ports:
    - port: 5000
      targetPort: 5000