apiVersion: v1
kind: Service # Service Object
metadata:
  name: postgres-cluster-ip-service
spec: # Service configuration
  type: ClusterIP
  selector:
    component: postgres # Same as pod metadata. What set of pods this service should provide access to.
  ports:
    - port: 5432
      targetPort: 5432